
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace ToxicModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ToxicModel.ModelInput sampleData = new ToxicModel.ModelInput()
            {
                Worker_id = @"4RHRV9MACQGW",
                Task_id = @"ccd0a1da-0e6a-453e-a6d1-6418cc4a5546",
                Task_response_id = @"3d66075c-623e-4e64-93ac-123d379d28f0",
                Text = @"I came here to say this exactly!",
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual IsToxic with predicted IsToxic from sample data...\n\n");


            Console.WriteLine($"Worker_id: {@"4RHRV9MACQGW"}");
            Console.WriteLine($"Task_id: {@"ccd0a1da-0e6a-453e-a6d1-6418cc4a5546"}");
            Console.WriteLine($"Task_response_id: {@"3d66075c-623e-4e64-93ac-123d379d28f0"}");
            Console.WriteLine($"Text: {@"I came here to say this exactly!"}");
            Console.WriteLine($"IsToxic: {@"0"}");


            var sortedScoresWithLabel = ToxicModel.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
